### ISSUE TITLE
error parsing login result page

### ISSUE THREAD

**Issue by JustJane86** [HitomaruKonpaku/SadPanda#12]
when I attempt to log in I get a little red box that says "error parsing login result page." my login works on both the forums and the main e-hentai site and my account is at least a month old.

I saw that back in march people were having this problem but it got solved. unfortunately for me it's still happening. 

https://ibb.co/KKxPSvv

**Comment by HitomaruKonpaku** [comment]
I believe you didnt use this extension.

That is UI from old extension

**Comment by JustJane86** [comment]
you were absolutely correct. I somehow had version 2.6 off the chrome shop or wherever. sorry I missed that detail. I downloaded and followed the directions to get the version 4.2

however now that I've updated I'm having the page reload on login bug that already has an open issue thread. I'll post there instead. 

thank you for swiftly spotting my problem.
