### ISSUE TITLE
Error: Error parsing login result page!

### ISSUE THREAD

**Issue by jesterjacks** [HitomaruKonpaku/SadPanda#13]
I tried to see a fix from others, but I'm getting an error with parsing login. I used to be able to get into exhent and then I cleared all my cookies, now I can't get into it, despite having done a clear re-install of the extension and cookies reset.

https://gyazo.com/243152142b39b8f920492c0b3376e97f
https://gyazo.com/e405ab11687ba3a3a614ce879b42aa80

**Comment by FunkyJustin** [comment]
I'm experiencing the same problem.

**Comment by UnderHigh** [comment]
I'm also having this problem..
