### ISSUE TITLE
Doesn't log in only restarts

### ISSUE THREAD

**Issue by Lynxio** [HitomaruKonpaku/SadPanda#2]
Welp

**Comment by Avindoth** [comment]
I have had this problem as well. There is a flicker when loading the site now too that I don't remember being there before this issue started. 

When loading:

![panda1](https://user-images.githubusercontent.com/42563536/44379864-d2aa8e80-a4bc-11e8-8324-75386f557188.jpg)
![panda2](https://user-images.githubusercontent.com/42563536/44379865-d2aa8e80-a4bc-11e8-9563-65f0cefa4c53.jpg)
![panda3](https://user-images.githubusercontent.com/42563536/44379866-d2aa8e80-a4bc-11e8-9c46-034c0d339586.jpg)

When attempting to log in, it resets, showing the contents in picture 2 then 3 again.

**Comment by HitomaruKonpaku** [comment]
Fix via c77190582fb7eb6637b17181c8d013f83b68eeaf

Can you guys try again?

**Comment by CodeZeke123** [comment]
same also in mine
still looping in after login and back to login form again

**Comment by HitomaruKonpaku** [comment]
Please redownload & add the extension to chrome again
