### ISSUE TITLE
Can't login with the extension

### ISSUE THREAD

**Issue by bluefiberbread** [HitomaruKonpaku/SadPanda#6]
When I type in my username and password and hit "sign in", it brings me back to the login page. Am I doing something wrong? I used to have access to exhentai a long time ago but I can't access it anymore for some reason

**Comment by HitomaruKonpaku** [comment]
Can you check #4 first?

**Comment by bluefiberbread** [comment]
I'm not getting any messages that says "no account exists with my username"

I can make a video if you want

**Comment by bluefiberbread** [comment]
Here's the video https://puu.sh/C48yG/1126f45ab6.webm

I used to have full access to exhentai with my account a long time ago, no idea what's going on tbh

**Comment by wuliao3991** [comment]
Same problem here. Regiseted an account with ehentai.org in 2016. First time knew about exhentai today and it keeps bringing me back to the login page after I hit "sign in". How did you fix it? Should I wait for longer time and try again?

**Comment by FJEWHFWEFHJSALDHKSAFHQWFQWF** [comment]
Same problem here , any solutions?
