### ISSUE TITLE
Vivaldi, endless refreshing log in

### ISSUE THREAD

**Issue by Rumba2000** [HitomaruKonpaku/SadPanda#9]
Can't log in successfully. Log in window is refreshing all the time with the same communicate "Ready!", sometimes there is another communicate too "you're now logged in". 

![s1](https://user-images.githubusercontent.com/49096184/55276583-c3fb4400-52f5-11e9-8576-818f548630f1.jpg)

I think it might be similar to this issue: https://github.com/HitomaruKonpaku/SadPanda/issues/2 because from what I can see (screens) user there was using Vivaldi as am I. Please help, I could really use exhentai to work for me on Vivaldi.

specs:
Vivaldi 2.4.1488.35 (Stable channel) (64-bit) (browser itself is based on Chrome of course)
old exhentai account and can log in on different browser (based on Firefox)

**Comment by HitomaruKonpaku** [comment]
Not tried on Vivaldi yet

Did you try on Chrome?

**Comment by yahopa26** [comment]
This issue also happen when I use chrome.

**Comment by HitomaruKonpaku** [comment]
@yahopa26 What is your Chrome version? I dont have any problem on Chrome 73

**Comment by yahopa26** [comment]
Weave what I say above. I still haven't used the latest update before. 
With latest update, I can login normally. 
Sorry

**Comment by Rumba2000** [comment]
> Not tried on Vivaldi yet
> 
> Did you try on Chrome?

No, I'm not using Chrome at all. I see you changed something lately in "Reload exact sender tab" - that change seems to made me able to log in on exhentai successfully on Vivaldi. So it seems case is closed. Thank you very, very much :)

**Comment by HitomaruKonpaku** [comment]
@Rumba2000 oh glad it worked :)

**Comment by sweepsalt** [comment]
i have the same issue i'm using chrome 73
